shared:
  class_names: &class_names ["NOT_DUPLICATE", "DUPLICATE" ]  #HQ (target = 0): High-quality posts with 30+ score and without a single edit.
                                                            #LQ_CLOSE (target =1): Low-quality posts that were closed by the community without a single edit.
                                                            #LQ_EDIT (target =2)
  max_seq_size: &max_seq_size 32
  num_classes: &num_classes 2

model_params:
  model: NLPClassifierModel
  num_classes: *num_classes
  input_channels: 88
  hidden_size: 128
  num_layers: 2
  bidirectional: True

args:
  expdir: src
  baselogdir: logs_sibur
  verbose: True

runner_params:
  input_key: ["name_1", "name_2"]
  # network will returns dict, not single value, or list
  output_key: logits

stages:
  infer:
    state_params:
      main_metric: &reduced_metric f1_score
      minimize_metric: False
      num_epochs: 1

    data_params:
      num_workers: 2
      batch_size: 256
      per_gpu_scaling: True
      train_datapath: dataset/my_train.parquet
      test_datapath: dataset/my_test.parquet
      infer_datapath: dataset/true_test.parquet


    callbacks_params:

      prediction_callback:
        _wrapper:
          callback: ControlFlowCallback
          ignore_loaders: [train, valid]
        callback: PredictionCallback
        input_key: pair_id
        output_key: logits
        output_csv_path: prediction.csv



      saver:
        callback: CheckpointCallback
