shared:
  class_names: &class_names ["HQ", "LQ_CLOSE", "LQ_EDIT" ]  #HQ (target = 0): High-quality posts with 30+ score and without a single edit.
                                                            #LQ_CLOSE (target =1): Low-quality posts that were closed by the community without a single edit.
                                                            #LQ_EDIT (target =2)
  max_seq_size: &max_seq_size 32
  num_classes: &num_classes 3

model_params:
  model: NLPClassifierModel
  num_classes: *num_classes
  input_channels: 302

args:
  expdir: src
  baselogdir: logs
  verbose: True

runner_params:
  input_key: ["body", "title", "tags"]
  # network will returns dict, not single value, or list
  output_key: logits

stages:
  stage_train:
    state_params:
      main_metric: &reduced_metric f1_score
      minimize_metric: False
      num_epochs: 120

    data_params:
      num_workers: 2
      batch_size: 256
      per_gpu_scaling: True
      use_mock: False
      train_datapath: dataset/my_train.parquet
      test_datapath: dataset/my_test.parquet
      infer_datapath: dataset/test.parquet
      fasttext_model_path: pretrained_model/wiki.en

    scheduler_params:
       scheduler: ExponentialLR
       gamma: 0.975

    criterion_params:
      _key_value: True

      class:
        criterion: CrossEntropyLoss
    optimizer_params:
      optimizer: AdamW
      lr: 0.001
      weight_decay: 0.0001
      betas: [0.9, 0.99]


    callbacks_params:

      prediction_callback:
        _wrapper:
          callback: ControlFlowCallback
          ignore_loaders: [train, valid]
        callback: PredictionCallback
        input_key: Id
        output_key: logits
        output_csv_path: prediction.csv


      loss_class:
        _wrapper:
          callback: ControlFlowCallback
          ignore_loaders: infer
        callback: CriterionCallback
        input_key: target
        output_key: logits
        prefix: loss_class
        criterion_key: class

      accuracy_class:
        _wrapper:
          callback: ControlFlowCallback
          ignore_loaders: infer
        callback: AccuracyCallback
        input_key: target
        output_key: logits
        prefix: accuracy_class
        num_classes: *num_classes
      auc_class:
        _wrapper:
          callback: ControlFlowCallback
          ignore_loaders: infer
        callback: AUCCallback
        input_key: target_one_hot
        output_key: logits
        prefix: auc_class
        class_args: *class_names
      f1_class:
        _wrapper:
          callback: ControlFlowCallback
          ignore_loaders: infer
        callback: F1MetricCallback
        input_key: target
        output_key: logits
      cm_class:
        _wrapper:
          callback: ControlFlowCallback
          ignore_loaders: infer
        callback: ConfusionMatrixCallback
        input_key: target
        output_key: logits
        prefix: cm_class
        class_names: *class_names
        num_classes: *num_classes

      optimizer:
        callback: OptimizerCallback
        loss_key: loss_class
      scheduler:
        callback: SchedulerCallback
        reduced_metric: *reduced_metric
      saver:
        callback: CheckpointCallback
